//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsInfo
    {
        public int pID { get; set; }
        public string pName { get; set; }
        public string pCategory { get; set; }
        public Nullable<int> pQty { get; set; }
        public Nullable<double> pPrice { get; set; }
        public Nullable<int> pDiscount { get; set; }
    }
}
