//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement_EF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class dept_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dept_info()
        {
            this.employee_info = new HashSet<employee_info>();
        }
    
        [Display(Name ="Department Number")]
        [Required(ErrorMessage ="Dept no.should not be left blank ")]
        public int d_No { get; set; }
        [Display(Name = "Department Name")]
       
        public string d_Name { get; set; }
        [Display(Name = "Department Location")]
        [Required(ErrorMessage = "Dept location should not be left blank ")]
        public string d_Location { get; set; }
    
        public virtual deptname_info deptname_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_info> employee_info { get; set; }
    }
}
